name: Main

on:
  workflow_dispatch:
    inputs:
      Version:
        description: 'version to be released'
        required: true

#  push:
#    tags:
#      - "v*.*.*"

jobs:
  cache-build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Go & Fyne (GUI framework) dependecies
        run:  sudo apt-get update && sudo apt-get install -y golang gcc libgl1-mesa-dev xorg-dev
      - name: Build
        run: go build .
      - name: Rename For release
        run: cp awsroleswitcher  awsroleswitcherlinux
      - name: show files
        run: ls
      - uses: actions/cache@v3
        id: restore-build
        with:
          path: ./awsroleswitcherlinux
          key: ${{ github.sha }}-linux
  cache-build-mac:
    runs-on: macos-12
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: echo ${{ github.sha }} mac > awsroleswitchermac
      - name: Test
        run: cat awsroleswitchermac
      - uses: actions/cache@v3
        id: restore-build
        with:
          path: ./awsroleswitchermac
          key: ${{ github.sha }}-mac
  cache-use-build:
    name: Retrive linux build from cache
    runs-on: ubuntu-latest
    needs: [cache-build-linux,cache-build-mac]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        id: restore-build-linux
        with:
          path: ./awsroleswitcherlinux
          key: ${{ github.sha }}-linux
      - uses: actions/cache@v3  
        id: restore-build-mac
        with:
          path: ./awsroleswitchermac
          key: ${{ github.sha }}-mac
      - run: ls
