name: Release by version tag

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  cache-build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set tag env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Install Go & Fyne (GUI framework) dependecies
        run:  sudo apt-get update && sudo apt-get install -y golang gcc libgl1-mesa-dev xorg-dev
      - name: Build
        run: go build --ldflags "-X 'main.version=${{ env.RELEASE_VERSION }}'" .
      - name: Rename For release
        run: cp awsroleswitcher  awsroleswitcherlinux
      - name: show files
        run: ls
      - uses: actions/cache@v3
        id: restore-build
        with:
          path: ./awsroleswitcherlinux
          key: ${{ github.sha }}-linux

  cache-build-mac:
    runs-on: macos-12
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.x'
      - name: Build
        run: go build --ldflags "-X 'main.version=${{ env.RELEASE_VERSION }}'" .
      - name: Rename For release
        run: cp awsroleswitcher  awsroleswitchermac
      - uses: actions/cache@v3
        id: restore-build
        with:
          path: ./awsroleswitchermac
          key: ${{ github.sha }}-mac
  cache-use-build:
    name: Retrive builds from cache and release
    runs-on: ubuntu-latest
    needs: [cache-build-linux,cache-build-mac]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        id: restore-build-linux
        with:
          path: ./awsroleswitcherlinux
          key: ${{ github.sha }}-linux
      - uses: actions/cache@v3  
        id: restore-build-mac
        with:
          path: ./awsroleswitchermac
          key: ${{ github.sha }}-mac
      - name: Set execution priviliges
        run: chmod +x awsroleswitchermac && chmod +x awsroleswitcherlinux
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            awsroleswitchermac
            awsroleswitcherlinux


